- name: Add deploy authorized key to server
  hosts: site
  remote_user: root
  tasks:
    - name: Add user authorized key
      authorized_key:
        user: deploy
        key: "{{ lookup('file', 'files/deploy_rsa.pub') }}"
