- name: "Authorize"
  hosts: manager
  remote_user: root
  tasks:
    - name: Add user authorized key
      authorized_key:
        user: deploy
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
