version: '3.7'

services:
  gateway:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/html:/var/www/html:ro
      - ./docker/production/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - jenkins

  jenkins:
    build:
      context: ./docker/common/jenkins
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    volumes:
      - jenkins-data:/var/jenkins_home
      - docker-certs:/certs/client:ro
    depends_on:
      - docker

  docker:
    image: docker:dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
      - docker-data:/var/lib/docker

volumes:
  jenkins-data:
  docker-certs:
  docker-data:
